before:
  hooks:
    - bash -c "cd frontend && yarn && yarn run webpack --mode production"
builds:
  - id: default 
    env:
    - CGO_ENABLED=1
    main: ./cmd/webmentiond
    goos:
      - linux
    goarch:
      - amd64
archives:
  - wrap_in_directory: true
    builds:
      - default
    format: zip
    files:
      - frontend/css/**/*
      - frontend/dist/**/*
      - frontend/index.html
      - frontend/demo.html
      - pkg/server/migrations/**/*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
