name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v1.1.1
      with:
        go-version: "1.14.4"
    - name: Run tests
      run: go test ./...
  build-linux:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - uses: actions/setup-go@v1.1.1
      with:
        go-version: "1.14.4"
    - name: Create package
      run: sudo bash -c "wget https://github.com/goreleaser/goreleaser/releases/download/v0.138.0/goreleaser_amd64.deb && dpkg -i goreleaser_amd64.deb && goreleaser build --snapshot"
  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v1
    - name: Log into DockerHub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Build Docker image
      run: docker build -t zerok/webmentiond:latest .
    - name: Push image
      run: docker push zerok/webmentiond:latest
